version: 2

defaults: &defaults
  docker:
    - image: maven:3-jdk-12
      entrypoint: /bin/sh
  working_directory: ~/repo
  environment:
    MAVEN_OPTS: -Xmx3200m

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn -s .circleci/settings.xml clean install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Artifactory
          command: mvn -s .circleci/settings.xml deploy -DaltDeploymentRepository=snapshot::default::${CI_ARTIFACTORY_URL}/libs-snapshot

  release:
    <<: *defaults
    steps:
      - checkout
      - run: |
          OLD_VERSION=$(mvn -s .circleci/settings.xml -q \
            -Dexec.executable="echo" -Dexec.args='${project.version}' \
            --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
          NEW_VERSION="${OLD_VERSION/-SNAPSHOT/}"
          echo "Releasing $OLD_VERSION as $NEW_VERSION"
          mvn -s .circleci/settings.xml versions:use-releases
          mvn -s .circleci/settings.xml versions:set -DnewVersion="$NEW_VERSION"
          mvn -s .circleci/settings.xml deploy -DaltDeploymentRepository=release::default::${CI_ARTIFACTORY_URL}/libs-release
          git config user.name "RustamGimadiev"
          git config user.email "rgimadeiv@provectus.com"
          git add pom.xml
          git commit -m "release: $NEW_VERSION"
          git tag "$NEW_VERSION"
          git checkout master
          git merge --no-edit release
          git push origin master --tags
          MAJ_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 1)
          MIN_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 2)
          NEW_MINOR=$(($MIN_VERSION + 1))
          DEV_VERSION="$MAJ_VERSION.$NEW_MINOR-SNAPSHOT"
          git checkout verify
          git merge --no-edit release
          mvn -s .circleci/settings.xml versions:set -DnewVersion="$DEV_VERSION"
          git add pom.xml
          git commit -m "ready for development: $DEV_VERSION"
          git push origin verify
          git push origin :release
  

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^master$/
      - release:
          requires:
            - build
          filters:
            branches:
              only: /^release$/
